const { GoogleGenerativeAI } = require("@google/generative-ai");

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

const model = genAI.getGenerativeModel({
  model: "gemini-2.5-flash",
});

const FEEDBACK_PROMPT = `
You are an expert behavioral interview evaluator.

You will receive a complete interview transcript between an interviewer and a candidate.

Evaluate the candidate based on:

- Communication clarity
- STAR Method
- Self-awareness
- Confidence
- Problem solving

IMPORTANT RULES:

1. Return ONLY valid JSON.
2. Do NOT use markdown.
3. Do NOT use \`\`\`json.
4. Do NOT explain anything.
5. Do NOT write any text before or after JSON.
6. Return exactly this structure.

{
  "overallScore": 8,
  "communicationScore": 8,
  "starStructureScore": 7,
  "selfAwarenessScore": 9,
  "strengths": "Write 2-3 sentences.",
  "improvements": "Write 2-3 sentences.",
  "fullReport": "Write a detailed report in plain text."
}
`;

async function generateFeedbackReport(messages) {
  const transcript = messages
    .map((m) =>
      `${m.role === "assistant" ? "Interviewer" : "Candidate"}: ${m.content}`
    )
    .join("\n");

  const prompt = `
${FEEDBACK_PROMPT}

Interview Transcript:

${transcript}
`;

  const result = await model.generateContent(prompt);

  const raw = result.response.text();

  console.log("\n================ GEMINI RAW RESPONSE ================\n");
  console.log(raw);
  console.log("\n=====================================================\n");

  // Remove markdown if Gemini adds it
  const cleaned = raw
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .trim();

  let parsed;

  try {
    parsed = JSON.parse(cleaned);
  } catch (err) {
    console.log("\n========== CLEANED RESPONSE ==========\n");
    console.log(cleaned);
    console.log("\n======================================\n");

    throw new Error("Gemini did not return valid JSON.");
  }

  const clamp = (n) =>
    Math.max(1, Math.min(10, Math.round(Number(n) || 5)));

  return {
    overallScore: clamp(parsed.overallScore),
    communicationScore: clamp(parsed.communicationScore),
    starStructureScore: clamp(parsed.starStructureScore),
    selfAwarenessScore: clamp(parsed.selfAwarenessScore),
    strengths:
      parsed.strengths ||
      "The candidate communicated reasonably well during the interview.",
    improvements:
      parsed.improvements ||
      "The candidate can improve by providing more structured answers.",
    fullReport:
      parsed.fullReport ||
      "No detailed feedback was generated by Gemini.",
  };
}

module.exports = {
  generateFeedbackReport,
};